---
title: Reflections on Progress and Poverty - Part I
date: 2024-04-07
tags: ["economics", "essay"]
---

**Author's note**: This work departs from the traditional essay format. It presents a series of personal annotations and critical reflections inspired by excerpts from Henry George’s seminal text, Progress and Poverty. Certain excerpts will be presented without additional commentary, allowing the power of George’s prose to speak for itself; for others, I will offer my own analysis. 

 Anyone that knows me is aware of my deep admiration for Henry George. For his sense of justice, his precision in thinking, his capacity for writing in a manner so moving that I can’t help but feel a profound love for humanity…these reflections of mine were a long time coming. 

 Link to a [PDF](https://drive.google.com/file/d/1UNypZ9iNtV43GzjioBHN8KkwWOCxK_Hq/view?usp=sharing).

---
---

The late 19th century in America was a period of rapid industrialization: transcontinental railroads stitched together a productive nation; large machines hummed with a newfound productivity enabled by a matured petroleum industry; and awesome fortunes were amassed at an unprecedented rate. Yet, amidst this time lurked a shadow that was perplexing in its persistence: widespread poverty. This period, famously satirized by Mark Twain as the “gilded age” for its *veneer* of prosperity that served only to mask deeper social ills (Twain, 1873), heavily impacted the American-Scotch Henry George (1839-1897). An outspoken self-taught economist and journalist, George would become a vocal critic of the prevailing economic orthodoxy, exposing in detail the injustice of rent-seeking and the private capture of unearned economic rents, specifically “ground rents”.

On asking a passing teamster while traveling to San Francisco “what the land was worth there” (Dodson, 2016), George, struck by epiphany, finally had answer as to why abject poverty could be but a stone’s throw away from the greatest wealth. Here was an explanation for the inexplicable condition of Dr. Jekyll (economic progress) and Dr. Hyde (poverty) that so befuddled intellectuals: “with the growth of population, land grows in value, and the men who work it must pay more for the privilege.” (Dodson, 2016). In recognizing how labor is increasingly held for ransom by rent, George undertook an independent line of inquiry without regard for the personal consequences of its conclusions, for “he who sees the truth, let him proclaim it, without asking who is for it or who is against it.”

His groundbreaking book, *Progress and Poverty: An Inquiry into the Cause of Industrial Depressions and of Increase of Want with Increase of Wealth: The Remedy*, is a careful examination of the root causes of inequality and economic instability within seemingly prosperous societies. In his treatise, George revives a radical solution---land value taxation---as a means to address these issues and engender a just and sound economic structure for society. My multi-part exploration will delve into the core arguments of *Progress and Poverty*: George’s examination of the seemingly paradoxical persistence of poverty amidst economic growth, his critique of prevailing economic theories, his emphasis on the “dual, not tripartite” primary division of wealth distribution, and finally an examination of the proposed solution of land value taxation. But first, let us say some more on the self-made American in order to convince ourselves of the good nature of the author whose work is under our study. In writing to his eighty-one year old father after a year and a half’s worth of toil whose final page drove him “in the dead of night [… to have] flung himself upon his knees and [weep] like a child”, Henry George wrote:

It is with deep feeling of gratitude to Our Father in Heaven that I send you a printed copy of this book. I am grateful that I have been enabled to live to write it, and that you have been enabled to live to see it. It represents a great deal of work and a good deal of sacrifice, but now it is done. It will not be recognized at first---maybe not for some time--—but it will ultimately be considered a great book, will be published in both hemispheres, and be translated into different languages. This I know, though neither of us may ever see it here. But the belief that I have expressed in this book---the belief that there is yet another life for us---makes that of little moment. 

 As shared in “How the Book Came to Be Written” by George’s son, Henry George, Jr.

George believed certain economic principles which had hitherto been neglected possessed something akin to the “inevitability and infallibility of the natural law of physics” (Hehner, 1993). While such unwavering confidence is appropriately a cause for skepticism, my first introduction to George through his compiled essays *Social Problems* and his magnum opus *Progress and Poverty* revealed a compelling argument. I found myself agreeing with an appeal to not underrate our innate capacity to grasp the commonsensical, for, “while we may not be scientists or philosophers we too are men.” (George, 1892). I found myself too, swayed by the candor of his prose, utterly convinced of his good-natured humanism, and touched by the purity of his deism. (And his particular choice in epigraphs, he always picks some great ones!)

*Progress and Poverty*, his first book, went on to sell “several million copies”, was translated in all the major languages, and fast became one of the best selling books of the late 1800s (Johnson, 1963). So catapulted was the celebrity of this man whose family was once in extreme privation that his popularity was rivaled only by his contemporaneous countrymen Mark Twain and Thomas Edison (Hehner, 1993). Even in more modern times, you need only read Henry George’s “Legacy” section on Wikipedia to see the prominent figures who had praise for him; sharing in my admiration are Albert Einstein, Martin Luther King, Leo Tolstoy, and Franklin D. Roosevelt (among many others). While George’s work achieved significant recognition in its time, his ideas have arguably become less prominent in contemporary economic discourse. The reasons for this relative obscurity remain a subject of debate, a topic left for the end of my series. (As a teaser: some contend that his ideas challenged the interests of powerful industrial tycoons who refused to surrender their golden-goose, i.e. rent-seeking, while others point to broader societal shifts that arguably lessened the perceived relevance of his land-centric critique, i.e. that the automobile and increasing suburbanization of America postponed the need to grapple with insensible land-use.)

Humbled by the job ahead of us to connect everything together but with a complete faith that “from various instruments, set to different keys, comes the grand harmony” (George, 1878), let us begin our examination.

## Book I - Wages and Capital
Book I and II of *Progress and Poverty* proceed by first undermining the arguments used in his day to explain poverty; these chiefly being the wage-fund theory, the Malthusian doctrine and others. With the prevailing wisdom convincingly debunked, George goes on to explain poverty as the natural consequence of the private capture of economic rents (namely ground rent) for which my own discussion and treatment will be addressed in the subsequent parts of this article.

### Defining Wealth and Capital: A Labor-Centric Perspective
Wealth and capital are often used interchangeably, this suffices in casual discussion. In formal contexts however, our language must be precise; a point belabored throughout the book. So let us properly define the two.

To George, “wealth […] consists of natural products that have been secured, moved, combined, separated, or in other ways modified by human exertion, so as to fit them for the gratification of human desires.” (Book I, Chapter II. The Meaning of the Terms)—wealth too is interpreted by George to be “stored up” labor, an accumulation of previous earnings just as “the heat of the sun is stored up in coal”. Wealth then is the outcome of labor’s application to natural resources which having been impressed with man’s spirit, can “minister to human desires”. Indeed, when taken globally, how enormous and endless is this desire! For “man is the only animal whose desires increase as they are fed; the only animal that is never satisfied” and for whom “the amount of wealth produced is nowhere commensurate with the desire for wealth, and desire mounts with every additional opportunity for gratification.” (Book IV, Chapter III. The Effect of the Improvements in the Arts upon the Distribution of Wealth). These quotes, as dogmatically as they are stated here, become evidently true in the many sections of the book that deal with it directly.

Then what is *capital*? To George, capital is but a subset of wealth as he asserts that “all capital is wealth, all wealth is not capital”, for capital is that portion actively devoted in the aid of production, e.g. machinery, buildings, and raw materials, whose ultimate use is the creation of additional goods and services. A more subtle implication becomes apparent when we take the framing of wealth as stored-up labor to its natural conclusion: “capital is [then] but a form of labor, and its distinction from labor is in reality but a subdivision, just as the the division of labor into skilled and unskilled would be.” (Book III, Chapter VI. Wages and the Law of Wages).

While some posit an inherent antagonism between capital and labor, with capital acting as a tyrannical oppressor, Henry George seeks to dispel this misconception. He argues that capital, far from being the enemy, is a vital tool—the laborer’s best friend---then still, labor being “deserv[ing] much the higher consideration”, as Abraham Lincoln aptly declared in his first annual address (Lincoln, 1861). Indeed, a symbiotic relationship exists: capital is not only the product and fruit of labor, but also its seed, demanding even further labor for its continued maintenance and expansion. That said, George identifies a key distortion in this dynamic when natural factors like land are introduced. The deprivation of either capital or labor, he contends, arises not from any inherent inter-conflict, but from the extraction of economic rents by landlords. These rents, levied on the land---the precursory foundation upon which both capital and labor operate---constitute an unearned gain whose private capture disrupts the natural equilibrium and hinders the just distribution of rewards. (George speaks mostly of spatial “ground rents” because of its magnitude and the diseconomies of improper land-use. However, there are other economic rents that he believes theoretically analogous.)

### The Wage-Fund Theory: A Critique
The wage-fund theory (or doctrine) holds that wages are paid out of some pool of capital, the wages themselves being determined by the ratio of available capital to the population of workers. From this we may draw two conclusions: (1) any worker earning relatively more does so to the detriment of another worker in zero-sum competition; and (2) wages tend to the minimum as the quantity of workers outstrips its pool of available capital, i.e. a population growth exceeding capital accumulation then inevitably results in poverty wages for all. Given the assumption that this pool of capital represents a fixed fund set aside for labor’s compensation, wages as such represent the advances made by capital due to labor. In sum, this theory casts wages and profits (the returns on capital) as inherently opposed while subordinating labor to capital, downplaying the role of labor in creating value and the concept of wages as its just and proper compensation. Once again, to George, this is a classic misconception.

As an explanation for the immiseration of workers that constitutes poverty, the wage-fund theory feels intuitive in its simplicity. That said, it clumsily trips over the same obstacles as does any zero-sum analysis of wealth; notably made impotent by its spurious assumptions that an “economic pie” is fixed or that overall wages can’t grow in tandem with overall profit--—these being either tenuous or outright disproven by reality.

To reject the wage-fund theory, George tackles foremost the erroneous view that wages are drawn as an advance from capital. George argues rather, that wages are drawn instead from the increase in the general stock of wealth that is directly attributable to its concomitant labor, i.e. wages are paid out of product. Why he chooses to do so rather than just reiterate the common rebuttals will later become clear as we set up the landscape that argues labor as being the primary driver of economic value creation.

We shall see clearly that in every case in which labor is exchanged for commodities, production really precedes enjoyment; that wages are the earnings—that is to say, the makings of labor—not the advances of capital, and that the laborer who receives his wages in money (coined or printed, it may be, before his labor commenced) really receives in return for the addition his labor has made to the general stock of wealth, a draft upon that general stock […] 

 *Chapter I. The Current Doctrine of Wages - Its Insufficiency*

### Rethinking Wages: An Earned Compensation from Product
To convince oneself of the header’s recharacterization, we must appreciate three things:

1. **Wages reflect value already created**. Earning (from labor) is synonymous to making (with labor)--—as George says, the expression “I made so and so” generally used to metaphorically mean “I earned so and so” is quite literally true economically speaking. Wages are not simply “making” money through labor; they represent compensation for value already added to the production process.

In George’s words: “As the rendering of labor precedes the payment of wages, and as the rendering of labor in production implies the creation of value, the employer receives value before he pays out value---*he but exchanges capital of one form for capital of another form*.” (Chapter III. Wages Not Drawn from Capital, but Produced by the Labor). The italicized notion of exchange here is important, it is essential to recognize the role of exchange within this system. Though money, particularly digital currency within online bank accounts, may obscure the underlying reality, all economic transactions ultimately represent a barter in the material domain. Similar to the laws of thermodynamics, wealth is not destroyed in an exchange, but rather transformed. Spending currency, whether physical or digital, signifies the exchange of an IOU against the collective wealth denominated in some currency (e.g. the US dollar) for a tangible good (e.g. a Rolex). The market dictates the dynamic pricing of these goods, just as it influences the value of the currency itself, but the fact remains that its utility eventually comes down to a greater or weaker claim on any *physical* good or service. Double-entry bookkeeping might capture this exchange, reflecting the *transfer* of value from one form (US dollars) to another ( Rolex) within an individual’s cash and inventory accounts (as opposed to its *destruction*).

2. **Wages are properly the recognition of an increase in wealth**. Traditionally, wages are viewed as an “advance” from a pre-existing pool of capital. However, a more accurate perspective suggests wages as an obligation or draft upon the newly created wealth. As labor is applied, the overall stock of wealth increases and so wages represent a rightful claim on this newly created value, not a loan or advance from any fixed pool.

From an economic perspective, wages can demonstrably be viewed as a form of post-facto compensation for value creation already realized through labor. The sequential relationship being one wherein the value created from the application of labor to the material precedes the payment of wages. Wages are thus not an advance on future production or capital, but rather a retrospective recognition of economic value already or currently added. What’s more, the value is continuous and additive throughout production (supposing labor is always productive) and while the incremental value creation can be interrupted by depreciation or entropy, the core principle remains---labor continuously adds value until the good or service reaches its final state. Where, once at said final state, the good or service possesses its final market value, i.e. its (marginal) utility, and thus reflects the culmination of all labor inputs through the chain of production. (Indirect labor in the way of managerial, design, or operational work are contributions that can be considered among more direct labor inputs.) Even partially completed goods or gathered materials embody an inherent value due to the labor already invested, in Newton’s parlance, they possess a *vis insita* of a different sort. When we acknowledge the continuous nature of value creation and the sequential relationship between labor and wages, the centrality of labor in the overall economic picture becomes evident. This perspective weakens arguments based on a fixed “wage fund” and strengthens the case for workers receiving a fair share of the value they demonstrably create, not just a portion of a pre-determined pool. George reaffirms the vital point succinctly: “no matter how long the process in which it is engaged, labor always adds to capital by its exertion before it takes from capital in its wages” (Chapter III. Wages Not Drawn from Capital but Produced by the Labor).

3. **Labor and capital really represent a synergistic relationship**: the two being faces of the same coin---human exertion---destined to grow or decline in tandem. While the latter parts of this paper will delve deeper into the relationship between labor and capital, it’s crucial to acknowledge their interdependence. Capital goods (e.g. machinery and tools) undoubtedly play a role in production; however, it’s essential to recognize that the creation and maintenance of these capital goods themselves require human labor. In this way, labor can be seen as the foundational element that drives the creation and utilization of capital. This interconnectedness strengthens the argument that wages are really a recognition of the value added through the (often intentional) combined efforts of both labor and capital.

Henry George was not alone in his interpretation of wages and labor. Adam Smith too emphasized the direct connection between labor and its wages. As is said by Adam Smith and repeated by George, “In that original state of things which precedes both the appropriation of land and the accumulation of stock, the whole produce of labor belongs to the laborer.” (Book I, Chapter III. Wages Not Drawn from Capital, but Produced by the Labor). In the laborer going to the unowned stream with a fishing rod of her own creation, and from her past exertion in the rod’s construction and her present exertion in fishing, her just wages are drawn directly from nature with each successful catch. In this pre-capitalist, pre-landowner scenario, the laborer is not beholden to a capitalist for her wages, but rather receives the full fruits of her labor. (When the stream is owned by a landlord, we will see how the rent unjustly takes from her wages.)

It is important to acknowledge the limitations of the current discussion: (1) thus far we’ve only focused on two (labor and capital) of the three classical factors of production: these being labor, capital, and land (or natural bounty). In linking capital and labor, we’ve come closer to George’s final contention on the actual “primary division of wealth in distribution [being] dual, not tripartite”---labor, capital (but a form of labor), and land; and (2) while its been established that labor is capital’s precursor and partner, the former being entitled to wages and the latter entitled to profits (or “interest” as we’ll see in our special treatment of capital); it is however, the third factor, land, or rather all of nature’s bounty and opportunity, that is the precursor of both. No productive enterprise can be achieved without land or its material and natural opportunity, even if trivially it refers only to the spatial volume one must occupy just to exist. In the solar system assembled in *Progress and Poverty*, land is the sun, labor the planets, and capital its moons; it is as if we are Copernicus, the solar system will become clear in due time.

### Labor in Systems of Exchange
George suggests that through exchange, individuals are indirectly accessing the value created by the labor of others, essentially “trading labor for labor”; that’s to say, if some forager “digs roots and exchanges them for venison, he is in effect as truly the procurer of the venison as though he had gone in chase of the deer and left the huntsman to dig his own roots.” (Book I, Chapter I. The Current Doctrine of Wages - Its Insufficiency).

Agents in early pre-currency barter systems directly exchanged products with intrinsic utility (e.g., livestock for tools). In such modes of exchange, the connection between one’s labor and the acquired good is easily apparent. However, with the development of “proto-money” (e.g. cowrie shells, precious metals and other things that were at once durable, portable and divisible), and eventually, modern currencies, this connection has become abstracted along more complex and longer chains of production and exchange.

That the “demand for consumption determines the direction [and degree] in which labor will be expended in production” (Book I, Chapter IV. The Maintenance of Laborers Not Drawn from Capital) is to me an obviously true but underrated statement (i.e. things are produced because someone demands them). I admit however that while consumer demand might set the general direction of production, other factors like efficiency, resource availability, and technological advancements may influence the “degree” of the labor equipped or willing to meet that demand.

Suppose my ability to produce from my labor is varied, be it toys, furniture, or clothing. But suppose however that my demand is singular, I crave only a particular type of milk. In exerting my labor, either in the employ of another or myself, my wages are directly the product of labor in the former and money (generally speaking) in the latter. My monetary compensation reflects how society has effectively directed my labor in the satiation of another’s desires in the form of toys and furniture, and that I am paid wages links us: the reciprocative satiation of my own material desires too. George highlights this by stating that “in aiding in the production of what other producers want, [I have directed] other labor to the production of the things [I] want.” (Book I, Chapter IV. The Maintenance of Laborers Not Drawn from Capital).

Complicating things somewhat is the aspect of money, for it is not entirely correct to say that the product of labor, i.e. a toy, is identical to the money I received for my labor’s value. A value which for all intents and purposes we may think as that which accumulates gradually to meet with the prevailing market price and thereafter follow. Here, money acts only as a convenient intermediary---a claim on society's “common stock” (George’s term), with which we can make financial or operational arrangements (e.g. financial derivatives or economic specialization) that do not themselves *really* constitute wealth or capital but may facilitate it. There are certain limitations to money itself, which restated, represent a claim on society’s output but may gain or lose purchasing power with its deflation or inflation. Money is a convenient means of facilitating exchange, not its source of value, for remember that the *original* source of value is the exertion of labor and whose value thereafter might be made dynamic by various other factors, the most dominant of which are the subjectivity of human desires across space and time, the variability of comparative advantage, and the quantity of physical stock marginally available for consumption, i.e. scarcity.

No nation would trade among itself for the sole purpose of money except that that money be used in the immediate employ of some useful thing, be that it may capital or wealth, for the sake of further production or consumption. That country A has given $$x$$ million dollars in aid to country B is often misleading. When we inspect more closely what that means, we find that country A has really given country B equipment, foodstuffs, clothing, etc. that are equivalent at some particular instant to $$x$$ million dollars. That it is $$x$$ million dollars at that particular time really just means it could be used to exchange for $$x$$ million dollars worth of something other than the equipment, foodstuffs, et cetera, also at that particular time. Were this a system wherein which you couldn’t exchange for anything besides the goods already mentioned or for which all production was already accounted for and at its limit, $$x$$ million dollars is an entirely meaningless term as it cannot be “spent” towards marginal production or consumption. It is similar to how a trader might rejoice at the extraordinary price his stock is trading at only to become utterly demoralized on the realization that its illiquidity means he has no counterparty to sell it to; or how a short-seller who successfully predicted and went short into nuclear armageddon would weep that the many millions of unrealized dollars in their brokerage account can fetch little else but radioactive ash. And so, even in seemingly non-labor transactions or those mediated as price in money or some other financial instrument, the underlying principle of productive exchange finally being the “trading labor for labor” persists.

### A Conclusion. For now
And so concludes the first part of this article. Where did we come from? We asserted repeatedly that wages are not an advance from capital but taken from the product of labor which precedes it. We affirmed that capital is but a subset of wealth, and further, a subdivision of labor---further too we affirmed the symbiotic, friendly relationship between capital and labor and alluded to the disharmonies caused by the introduction of land rents. Finally, we dealt with at length the notion that all exchange ultimately comes down to the trading of labor for labor.

The next part will focus on the next few books of *Progress and Poverty*. The first book under our future consideration is Book II which starts with a proper dismantlement of the Malthusian doctrine: first by charitably restating it, succeeded by exposing its weaknesses, and then finally putting it to rest. (Malthusianism is overwhelmingly rejected in the modern day, but was in George’s time a very influential theory that affected policy, religion and private charity. In keeping with the historical context, we’ll be careful here too in our discussion.)

Till next time.

---
---

### References 
Progress and Poverty. (1879). Progress and Poverty: An Inquiry into the Cause of Industrial Depressions and of Increase of Want with Increase of Wealth: The Remedy. Henry George

Wikimedia Foundation. (2023, September 14). Henry George. Wikipedia. https://en.wikipedia.org/wiki/Henry_George

Wikimedia Foundation. (2023, August 22). Progress and Poverty. Wikipedia. https://en.wikipedia.org/wiki/Progress_and_Poverty

Cooperative Individualism. (1993, October). Henry George: Inspiration for Truth-Seekers. Dr. Cay Hehner. https://cooperative-individualism.org/hehner-cay_henry-george-inspiration-for-truth-seekers-1993-sep-oct.pdf

Henry George. (1892). A Perplexed Philosopher. Henry George. https://bibliotek1.dk/english/by-henry-george/a-perplexed-philosopher

The American Presidency Project. (1861). First Annual Message. Abraham Lincoln. https://www.presidency.ucsb.edu/documents/first-annual-message-9

Penguin Random House. (1873). The Gilded Age. Mark Twain. https://www.penguinrandomhouse.com/books/292277/the-gilded-age-by-mark-twain-and-charles-dudley-warner/

Cooperative Individualism. (2016, October). A Chronology of the Life and Work of Henry George. Edward J. Dodson. https://cooperative-individualism.org/dodson-edward_a-chronology-of-the-life-and-work-of-henry-george.htm

Econlib. (1905, January). On How the Book came to be Written. Henry George, Jr. https://www.econlib.org/book-chapters/chapter-how-the-book-came-to-be-written-by-henry-george-jr/

The Museum of the City of San Franciscan. (1963, March). Progress and Poverty—a Paradox. Kenneth M. Johnson. http://sfmuseum.org/hist9/hgeorge.html